---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: streaming-pv
  labels:
    app: streaming-store
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/persistence-store/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
