apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-core
  template:
    metadata:
      labels:
        app: streaming-core
    spec:
      volumes:
      - name: file-store
        persistentVolumeClaim:
          claimName: streaming-pv-claim
      containers:
        - name: streaming-core
          image: docker.io/abarrak/streaming-system-streaming-core:0.1
          imagePullPolicy: Always
          ports:
          - name: core-port
            containerPort: 9100
          volumeMounts:
          - mountPath: "/usr/file-store"
            name: file-store
          env:
          - name: FileStorePath
            value: "/usr/file-store"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoding-core
spec:
  selector:
    matchLabels:
      app: encoding-core
  template:
    metadata:
      labels:
        app: encoding-core
    spec:
      volumes:
      - name: file-store
        persistentVolumeClaim:
          claimName: streaming-pv-claim
      containers:
      - name: encoding-core
        image: docker.io/abarrak/streaming-system-encoding-core:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: "/usr/file-store"
          name: file-store
        env:
        - name: FileStorePath
          value: "/usr/file-store"
        - name: ConnectionStrings__Sqlite
          value: "Data Source=/usr/db/database.db"
        command:
          - "sudo yum install epel-release -y"
          - "sudo yum localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm -y"
          - "sudo yum install ffmpeg ffmpeg-devel -y"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: file-store
        persistentVolumeClaim:
          claimName: streaming-pv-claim
      containers:
      - name: web
        image: docker.io/abarrak/streaming-system-web:0.1
        imagePullPolicy: Always
        ports:
        - name: web-port
          containerPort: 9200
        volumeMounts:
        - mountPath: "/usr/file-store"
          name: file-store
        env:
        - name: FileStorePath
          value: "/usr/file-store"
        - name: ConnectionStrings__Sqlite
          value: "Data Source=/usr/db/database.db"
        - name: StreamingServerUrl
          value: $(STREAMING-CORE-SVC_SERVICE_HOST)
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-core-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: core-port
  selector:
    app: streaming-core
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: web-port
  selector:
    app: web
