apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-core
  template:
    metadata:
      labels:
        app: streaming-core
    spec:
      containers:
        - name: streaming-core
          image: docker.io/abarrak/streaming-system-streaming-core:0.1
          imagePullPolicy: Always
          ports:
          - name: streaming-core-port
            containerPort: 9100
          env:
          - name: FileStorePath
            value: ""      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoding-core
spec:
  selector:
    matchLabels:
      app: encoding-core
  template:
    metadata:
      labels:
        app: encoding-core
    spec:
      containers:
      - name: encoding-core
        image: docker.io/abarrak/streaming-system-encoding-core:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: FileStorePath
          value: ""      
        - name: ConnectionStrings__Sqlite
          value: ""    
        - name: StreamingServerUrl
          value: ""      
        # command:
        #   - "sudo yum install epel-release -y"
        #   - "sudo yum localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm -y"
        #   - "sudo yum install ffmpeg ffmpeg-devel -y"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: docker.io/abarrak/streaming-system-web:0.1
        imagePullPolicy: Always
        ports:
        - name: web-port
          containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-core-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: streaming-core-port
  selector:
    app: streaming-core
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: web-port
  selector:
    app: web
