---
apiVersion: v1
kind: Service
metadata:
  name: core-svc
spec:
  ports:
  - port: 80
    targetPort: core-port
  selector:
    app: streaming-core
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  ports:
  - port: 8050
    targetPort: web-port
  selector:
    app: web
